#From: https://learn.gencore.bio.nyu.edu/rna-seq-analysis/gene-set-enrichment-analysis/

BiocManager::install("org.Mm.eg.db")
BiocManager::install("org.Dm.eg.db")
BiocManager::install("clusterProfiler", version = "3.14")
BiocManager::install("pathview")
BiocManager::install("enrichplot")
install.packages("ggridges")
install.packages("gridExtra")

library(clusterProfiler)
library(enrichplot)
library(tidyverse)
library(magrittr)
library(dplyr)
library(DESeq2)
library(RColorBrewer)
library(pheatmap)
library(ggplot2)
library(ggridges)
library(gridExtra)

organism = "org.Mm.eg.db" #setting desired organism
BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)#bioconductor organism annotation library

amg = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/vp_a.csv", header=TRUE)
nac = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/vp_n.csv", header=TRUE)
vta = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/vp_v.csv", header=TRUE)
pfc = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/vp_p.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list_amg <- amg$log2FoldChange
original_gene_list_nac <- nac$log2FoldChange
original_gene_list_vta <- vta$log2FoldChange
original_gene_list_pfc <- pfc$log2FoldChange


# name the vector
names(original_gene_list_amg) <- amg$X
names(original_gene_list_nac) <- nac$X
names(original_gene_list_vta) <- vta$X
names(original_gene_list_pfc) <- pfc$X


# omit any NA values 
gene_list_amg<-na.omit(original_gene_list_amg)
gene_list_nac<-na.omit(original_gene_list_nac)
gene_list_vta<-na.omit(original_gene_list_vta)
gene_list_pfc<-na.omit(original_gene_list_pfc)

# sort the list in decreasing order (required for clusterProfiler)
gene_list_amg = sort(gene_list_amg, decreasing = TRUE)
gene_list_nac = sort(gene_list_nac, decreasing = TRUE)
gene_list_vta = sort(gene_list_vta, decreasing = TRUE)
gene_list_pfc = sort(gene_list_pfc, decreasing = TRUE)

keytypes(org.Mm.eg.db)#what kind of gene identifers can I use?


##AMYGDALA##///////////////////////////////////////////////////////////////////
gse_amg <- gseGO(geneList=gene_list_amg, 
             ont ="MF", 
             keyType = "SYMBOL", 
             minGSSize = 5, 
             maxGSSize = 500, 
             pvalueCutoff = 0.1, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")


#Dotplot
require(DOSE)
dotplot(gse_amg, showCategory = 10, title = "Enriched MF Pathways - AMYGDALA" , 
        split=".sign") + facet_grid(.~.sign)

?dotplot

#"Grouped by gene set, density plots are generated by using the frequency of fold change 
#values per gene within each set. Helpful to interpret up/down-regulated pathways."
ridgeplot(gse_amg) + labs(x = "Enrichment Distribution")

##NUCLEUS ACCUMBENS##//////////////////////////////////////////////////////////
gse_nac <- gseGO(geneList=gene_list_nac, 
                 ont ="MF", 
                 keyType = "SYMBOL", 
                 minGSSize = 5, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.1, 
                 verbose = TRUE, 
                 OrgDb = organism, 
                 pAdjustMethod = "none")


l#Dotplot
dotplot(gse_nac, showCategory = 10, title = "Enriched MF Pathways - NUCLEUS ACCUMBENS" , 
        split=".sign") + facet_grid(.~.sign)

#Ridgeplot
ridgeplot(gse_nac) + labs(x = "Enrichment Distribution")

##VENTRAL TEGMENTAL AREA##/////////////////////////////////////////////////////
gse_vta <- gseGO(geneList=gene_list_vta, 
                 ont ="MF", 
                 keyType = "SYMBOL", 
                 minGSSize = 5, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.1, 
                 verbose = TRUE, 
                 OrgDb = organism, 
                 pAdjustMethod = "none")


#Dotplot
dotplot(gse_vta, showCategory = 10, title = "Enriched Pathways - VENTRAL TEGMENTAL AREA" , 
        split=".sign") + facet_grid(.~.sign)

#Ridgeplot
ridgeplot(gse_vta) + labs(x = "Enrichment Distribution")

##PREFRONTAL CORTEX##/////////////////////////////////////////////////////
gse_pfc <- gseGO(geneList=gene_list_pfc, 
                 ont ="MF", 
                 keyType = "SYMBOL", 
                 minGSSize = 5, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.1, 
                 verbose = TRUE, 
                 OrgDb = organism, 
                 pAdjustMethod = "none")


#Dotplot
dotplot(gse_pfc, showCategory = 10, title = "Enriched Pathways - PREFRONTAL CORTEX" , 
        split=".sign") + facet_grid(.~.sign)

#Ridgeplot
ridgeplot(gse_pfc) + labs(x = "Enrichment Distribution")

###############################################################################
###############################################################################
#Group family photo

amgd <- dotplot(gse_amg, showCategory = 20, title = "Enriched MF Pathways - AMYGDALA" , 
        split=".sign") + facet_grid(.~.sign)
nacd <- dotplot(gse_nac, showCategory = 20, title = "Enriched MF Pathways - NUCLEUS ACCUMBENS" , 
                split=".sign") + facet_grid(.~.sign)
vtad <- dotplot(gse_vta, showCategory = 20, title = "Enriched MF Pathways - VENTRAL TEGMENTAL AREA" , 
                split=".sign") + facet_grid(.~.sign)
pfcd <- dotplot(gse_pfc, showCategory = 20, title = "Enriched MF Pathways - PREFRONTAL CORTEX" , 
                split=".sign") + facet_grid(.~.sign)

##////////////////////////////////////////////// AMYG RIDGEPLOT

amg_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_amyg_up.csv", header=TRUE)

amg_up_p = filter(amg_up, pvalue <=.05)

original_gene_list_amg_up <- amg_up_p$log2FoldChange

names(original_gene_list_amg_up) <- amg_up_p$X

gene_list_amg_up<-na.omit(original_gene_list_amg_up)

gene_list_amg_up = sort(gene_list_amg_up, decreasing = TRUE)

gse_amg_up <- gseGO(geneList=gene_list_amg_up, 
                 ont ="ALL", 
                 keyType = "SYMBOL", 
                 minGSSize = 5, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.15, 
                 verbose = TRUE, 
                 OrgDb = organism, 
                 pAdjustMethod = "fdr")

amgr_up <-ridgeplot(gse_amg_up) + labs(x = "Enrichment Distribution", title = "Enriched UPREGULATED MF Pathways - AMYGDALA")
##
amg_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_amyg_down.csv", header=TRUE)

amg_down_p = filter(amg_down, pvalue <=.05)

original_gene_list_amg_down <- amg_down_p$log2FoldChange

names(original_gene_list_amg_down) <- amg_down_p$X

gene_list_amg_down<-na.omit(original_gene_list_amg_down)

gene_list_amg_down = sort(gene_list_amg_down, decreasing = TRUE)

gse_amg_down <- gseGO(geneList=gene_list_amg_down, 
                    ont ="MF", 
                    keyType = "SYMBOL", 
                    minGSSize = 5, 
                    maxGSSize = 500, 
                    pvalueCutoff = 0.15, 
                    verbose = TRUE, 
                    OrgDb = organism, 
                    pAdjustMethod = "fdr")

amgr_down <-ridgeplot(gse_amg_down) + labs(x = "Enrichment Distribution", title = "Enriched DOWNREGULATED MF Pathways - AMYGDALA")
###
nac_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_nac_up.csv", header=TRUE)

nac_up_p = filter(nac_up, pvalue <=.05)

original_gene_list_nac_up <- nac_up_p$log2FoldChange

names(original_gene_list_nac_up) <- nac_up_p$X

gene_list_nac_up<-na.omit(original_gene_list_nac_up)

gene_list_nac_up = sort(gene_list_nac_up, decreasing = TRUE)

gse_nac_up <- gseGO(geneList=gene_list_nac_up, 
                      ont ="MF", 
                      keyType = "SYMBOL", 
                      minGSSize = 5, 
                      maxGSSize = 500, 
                      pvalueCutoff = 0.15, 
                      verbose = TRUE, 
                      OrgDb = organism, 
                      pAdjustMethod = "fdr")

nac_up <-ridgeplot(gse_nac_up) + labs(x = "Enrichment Distribution", title = "Enriched UPREGULATED MF Pathways - NUCLEUS ACCUMBENS")
##
nac_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_nac_down.csv", header=TRUE)

nac_down_p = filter(nac_down, pvalue <=.05)

original_gene_list_nac_down <- nac_down_p$log2FoldChange

names(original_gene_list_nac_down) <- nac_down_p$X

gene_list_nac_down<-na.omit(original_gene_list_nac_down)

gene_list_nac_down = sort(gene_list_nac_down, decreasing = TRUE)

gse_nac_down <- gseGO(geneList=gene_list_nac_down, 
                      ont ="MF", 
                      keyType = "SYMBOL", 
                      minGSSize = 5, 
                      maxGSSize = 500, 
                      pvalueCutoff = 0.15, 
                      verbose = TRUE, 
                      OrgDb = organism, 
                      pAdjustMethod = "fdr")

nac_down <-ridgeplot(gse_nac_down) + labs(x = "Enrichment Distribution", title = "Enriched DOWNREGULATED MF Pathways - NUCLEUS ACCUMBENS")
###
vta_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_vta_up.csv", header=TRUE)

vta_up_p = filter(vta_up, pvalue <=.05)

original_gene_list_vta_up <- vta_up_p$log2FoldChange

names(original_gene_list_vta_up) <- vta_up_p$X

gene_list_vta_up<-na.omit(original_gene_list_vta_up)

gene_list_vta_up = sort(gene_list_vta_up, decreasing = TRUE)

gse_vta_up <- gseGO(geneList=gene_list_vta_up, 
                    ont ="MF", 
                    keyType = "SYMBOL", 
                    minGSSize = 5, 
                    maxGSSize = 500, 
                    pvalueCutoff = 0.15, 
                    verbose = TRUE, 
                    OrgDb = organism, 
                    pAdjustMethod = "fdr")

vta_up <-ridgeplot(gse_vta_up) + labs(x = "Enrichment Distribution", title = "Enriched UPREGULATED MF Pathways - VENTRAL TEGMENTAL AREA")
##
vta_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_vta_down.csv", header=TRUE)

vta_down_p = filter(vta_down, pvalue <=.05)

original_gene_list_vta_down <- vta_down_p$log2FoldChange

names(original_gene_list_vta_down) <- vta_down_p$X

gene_list_vta_down<-na.omit(original_gene_list_vta_down)

gene_list_vta_down = sort(gene_list_vta_down, decreasing = TRUE)

gse_vta_down <- gseGO(geneList=gene_list_vta_down, 
                      ont ="MF", 
                      keyType = "SYMBOL", 
                      minGSSize = 5, 
                      maxGSSize = 500, 
                      pvalueCutoff = 0.15, 
                      verbose = TRUE, 
                      OrgDb = organism, 
                      pAdjustMethod = "fdr")

vta_down <-ridgeplot(gse_vta_down) + labs(x = "Enrichment Distribution", title = "Enriched DOWNREGULATED MF Pathways - VENTRAL TEGMENTAL AREA")
###
pfc_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_pfc_up.csv", header=TRUE)

pfc_up_p = filter(pfc_up, pvalue <=.05)

original_gene_list_pfc_up <- pfc_up_p$log2FoldChange

names(original_gene_list_pfc_up) <- pfc_up_p$X

gene_list_pfc_up<-na.omit(original_gene_list_pfc_up)

gene_list_pfc_up = sort(gene_list_pfc_up, decreasing = TRUE)

gse_pfc_up <- gseGO(geneList=gene_list_pfc_up, 
                    ont ="MF", 
                    keyType = "SYMBOL", 
                    minGSSize = 5, 
                    maxGSSize = 500, 
                    pvalueCutoff = 0.15, 
                    verbose = TRUE, 
                    OrgDb = organism, 
                    pAdjustMethod = "fdr")

pfc_up <-ridgeplot(gse_pfc_up) + labs(x = "Enrichment Distribution", title = "Enriched UPREGULATED MF Pathways - PREFRONTAL CORTEX")
##
pfc_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/mouse_pfc_down.csv", header=TRUE)

pfc_down_p = filter(pfc_down, pvalue <=.05)

original_gene_list_pfc_down <- pfc_down_p$log2FoldChange

names(original_gene_list_pfc_down) <- pfc_down_p$X

gene_list_pfc_down<-na.omit(original_gene_list_pfc_down)

gene_list_pfc_down = sort(gene_list_pfc_down, decreasing = TRUE)

gse_pfc_down <- gseGO(geneList=gene_list_pfc_down, 
                      ont ="MF", 
                      keyType = "SYMBOL", 
                      minGSSize = 5, 
                      maxGSSize = 500, 
                      pvalueCutoff = 0.15, 
                      verbose = TRUE, 
                      OrgDb = organism, 
                      pAdjustMethod = "fdr")

pfc_down <-ridgeplot(gse_pfc_down) + labs(x = "Enrichment Distribution", title = "Enriched DOWNREGULATED MF Pathways - PREFRONTAL CORTEX")
################################################################################
require(gridExtra)
grid.arrange(amgr_up,amygr_down, ncol=4)


amgr <- ridgeplot(gse_amg) + labs(x = "Enrichment Distribution", title = "Enriched MF Pathways - AMYGDALA")
nacr <- ridgeplot(gse_nac) + labs(x = "Enrichment Distribution", title = "Enriched MF Pathways - NUCLEUS ACCUMBENa")
vtar <- ridgeplot(gse_vta) + labs(x = "Enrichment Distribution", title = "Enriched MF Pathways - VENTRAL TEGMENTAL AREA")
pfcr <- ridgeplot(gse_pfc) + labs(x = "Enrichment Distribution", title = "Enriched MF Pathways - PREFRONTAL CORTEX")

amgr_up
amgr_down
vta_down
pfc_up


grid.arrange(amgr_up,amgr_down,vta_down,pfc_up, ncol=2)

#////////////////////////////////////////////////////////enrichment
n_gene_list_amg_up <-names(gene_list_amg_up)

go_enrich_amg_up <- enrichGO(gene = n_gene_list_amg_up,
                      OrgDb = organism, 
                      keyType = 'SYMBOL',
                      readable = F,
                      ont = "BP",
                      pvalueCutoff = .05,
                      qvalueCutoff = .1,
                      pAdjustMethod = "bonferroni")

b_amy_up <- barplot(go_enrich_amg_up, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched UPREGULATED BP Annotations - AMYGDALA",
        font.size = 8)

n_gene_list_amg_down <-names(gene_list_amg_down)

go_enrich_amg_down <- enrichGO(gene = n_gene_list_amg_down,
                             OrgDb = organism, 
                             keyType = 'SYMBOL',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_amy_down <- barplot(go_enrich_amg_down, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched DOWNREGULATED BP Annotations - AMYGDALA",
        font.size = 8)
#!!!!!!!!!!!!!!!!

n_gene_list_vta_down <-names(gene_list_vta_down)

go_enrich_vta_down <- enrichGO(gene = n_gene_list_vta_down,
                             OrgDb = organism, 
                             keyType = 'SYMBOL',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_vta_down <- barplot(go_enrich_vta_down, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched DOWNREGULATED BP Annotations - VENTRAL TEGMENTAL AREA",
        font.size = 8)

n_gene_list_vta_up <-names(gene_list_vta_up)

go_enrich_vta_up <- enrichGO(gene = n_gene_list_vta_up,
                             OrgDb = organism, 
                             keyType = 'SYMBOL',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_vta_up <- barplot(go_enrich_vta_up, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched UPREGULATED BP Annotations - VENTRAL TEGMENTAL AREA",
        font.size = 8)

#!!!!!!!!!

n_gene_list_pfc_down <-names(gene_list_pfc_down)

go_enrich_pfc_down <- enrichGO(gene = n_gene_list_pfc_down,
                               OrgDb = organism, 
                               keyType = 'SYMBOL',
                               readable = F,
                               ont = "BP",
                               pvalueCutoff = .05,
                               qvalueCutoff = .1,
                               pAdjustMethod = "bonferroni")

b_pfc_down <- barplot(go_enrich_pfc_down, 
                      drop = TRUE, 
                      showCategory = 20, 
                      title = "Enriched DOWNREGULATED BP Annotations - PREFRONTAL CORTEX",
                      font.size = 8)

n_gene_list_pfc_up <-names(gene_list_pfc_up)

go_enrich_pfc_up <- enrichGO(gene = n_gene_list_pfc_up,
                             OrgDb = organism, 
                             keyType = 'SYMBOL',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_pfc_up <- barplot(go_enrich_pfc_up, 
                    drop = TRUE, 
                    showCategory = 20, 
                    title = "Enriched UPREGULATED BP Annotations - PREFRONTAL CORTEX",
                    font.size = 8)

#!!!!!!!

n_gene_list_nac_down <-names(gene_list_nac_down)

go_enrich_nac_down <- enrichGO(gene = n_gene_list_nac_down,
                               OrgDb = organism, 
                               keyType = 'SYMBOL',
                               readable = F,
                               ont = "BP",
                               pvalueCutoff = .05,
                               qvalueCutoff = .1,
                               pAdjustMethod = "bonferroni")

b_nac_down <- barplot(go_enrich_nac_down, 
                      drop = TRUE, 
                      showCategory = 20, 
                      title = "Enriched DOWNREGULATED BP Annotations - NUCLEUS ACCUMBENS",
                      font.size = 8)

n_gene_list_nac_up <-names(gene_list_nac_up)

go_enrich_nac_up <- enrichGO(gene = n_gene_list_nac_up,
                             OrgDb = organism, 
                             keyType = 'SYMBOL',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_nac_up <- barplot(go_enrich_nac_up, 
                    drop = TRUE, 
                    showCategory = 20, 
                    title = "Enriched UPREGULATED BP Annotations - NUCLEUS ACCUMBENS",
                    font.size = 8)

#!!!!!!!!!

n_gene_list_fly_up <-names(gene_list_fly_up)

go_enrich_fly_up <- enrichGO(gene = n_gene_list_fly_up,
                             OrgDb = organism_f, 
                             keyType = 'FLYBASE',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_fly_up <- barplot(go_enrich_fly_up, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched UPREGULATED BP Annotations - WHOLE BRAIN",
        font.size = 8)

n_gene_list_fly_down <-names(gene_list_fly_down)

go_enrich_fly_down <- enrichGO(gene = n_gene_list_fly_down,
                             OrgDb = organism_f, 
                             keyType = 'FLYBASE',
                             readable = F,
                             ont = "BP",
                             pvalueCutoff = .05,
                             qvalueCutoff = .1,
                             pAdjustMethod = "bonferroni")

b_fly_down <-barplot(go_enrich_fly_down, 
        drop = TRUE, 
        showCategory = 20, 
        title = "Enriched DOWNREGULATED BP Annotations - WHOLE BRAIN",
        font.size = 8)

#####
#Use https://biit.cs.ut.ee/gprofiler/gost for enrichment analysis


bird_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/finch_upreg_enrichment.csv", header=TRUE)
bird_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/finch_downreg_enrichment.csv", header=TRUE)

bird_up_up <-bird_up[,c(2:4,8)]
colnames(bird_up_up) <-c("Description","ID","p.adjust","Count")
bird_up_up <- bird_up_up[order(bird_up_up$p.adjust),]
bird_up_up_up <- bird_up_up[c(1:20),]

b_bird_up <-ggplot(data=bird_up_up_up, aes(y = reorder(Description, -p.adjust), x=Count, fill=p.adjust)) + 
  geom_bar(stat="identity") +
  theme(legend.position = "right",
        axis_text_y = element_text(color="#000000", size=rel(36), angle=90)) +
  labs(y = NULL, title = "Enriched UPREGULATED MF Annotations - T.GUTTATA AUDITORY CORTEX") +
  scale_fill_gradient(low="red", high="blue", 
                      limits = c(.04500, .04700)) +
  theme_bw()


bird_down_down <-bird_down[c(147:963),c(2:4,8)]
colnames(bird_down_down) <-c("Description","ID","p.adjust","Count")
bird_down_down <- bird_down_down[order(bird_down_down$p.adjust),]
bird_down_down_down <- bird_down_down[c(1:20),]

b_bird_down <-ggplot(data=bird_down_down_down, aes(y = reorder(Description, -p.adjust), x=Count, fill=p.adjust)) + 
  geom_bar(stat="identity") +
  theme(legend.position = "right") +
  labs(y = NULL, title = "Enriched DOWNREGULATED BP Annotations - T.GUTTATA AUDITORY CORTEX") +
  scale_fill_gradient(low="red", high="blue", 
                      limits = c(.000000520, .014549536)) +
  theme_bw()

grid.arrange(b_bird_up,b_bird_down,ncol=2)

#####

grid.arrange(b_amy_up,b_amy_down,b_nac_down,b_vta_up,b_vta_down,b_pfc_down,ncol=2)

library(gridExtra)
library(grid)
library(lattice)

t_amy_down <-textGrob(("No Significant DOWN AMG Terms"),gp = gpar(col = "black", fontsize = 20))
t_nac_down <-textGrob(("No Significant DOWN Nac Terms"),gp = gpar(col = "black", fontsize = 20))
t_pfc_up <-textGrob(("No Significant UP PFC Terms"),gp = gpar(col = "black", fontsize = 20))
murine_p <-textGrob(
  expression(bold("Murine DESeq2 Input Unadjusted P-value <.1
Murine BP GO Unadjusted P-value <.05, Q-value <.1 (Bonferroni)")),
  gp = gpar(col = "black", fontsize = 20))
fly_p <-textGrob(
  expression(bold("Fly DESeq2 Input Adjusted P-value <.1
Fly BP GO Unadjusted P-value <.05, Q-value <.1 (Bonferroni)")),
  gp = gpar(col = "black", fontsize = 20))
  
b_pfc_up

grid.arrange(b_nac_down,b_vta_down,b_pfc_down)
  
up_arrangement <-grid.arrange(b_amy_up,b_nac_up,b_vta_up,t_pfc_up,ncol=1)

down_arrangement <-grid.arrange(t_amy_down,t_nac_down,b_vta_down,b_pfc_down,ncol=1)

bp_arrangement <-grid.arrange(murine_p,fly_p,up_arrangement,down_arrangement,b_fly_up,b_fly_down,ncol=2)

grid.arrange(up_arrangement,down_arrangement, ncol=2)



library(cowplot)

plot_grid(murine_p, fly_p, up_arrangement, down_arrangement,b_fly_up, b_fly_down, align = "v", nrow = 3, ncol=2, rel_heights = c(1/24, 16/24, 7/24))

#[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
#Drosophila Ontology

organism_f = "org.Dm.eg.db" #setting desired organism
BiocManager::install(organism_f, character.only = TRUE)
library(organism_f, character.only = TRUE)#bioconductor organism annotation library

fly = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/res_f.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list_fly <- fly$log2FoldChange

# name the vector
names(original_gene_list_fly) <- fly$X

# omit any NA values 
gene_list_fly<-na.omit(original_gene_list_fly)

# sort the list in decreasing order (required for clusterProfiler)
gene_list_fly = sort(gene_list_fly, decreasing = TRUE)

keytypes(org.Dm.eg.db)#what kind of gene identifers can I use?

gse_fly <- gseGO(geneList=gene_list_fly, 
                 ont ="MF", 
                 keyType = "FLYBASE", 
                 nPerm = 10000, 
                 minGSSize = 5, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.05, 
                 verbose = TRUE, 
                 OrgDb = organism_f, 
                 pAdjustMethod = "none")


#Dotplot
dotplot(gse_fly, showCategory = 20, title = "Enriched MF Pathways - D. MELANOGASTER WHOLE BRAIN" , 
        split=".sign") + facet_grid(.~.sign)


#"Grouped by gene set, density plots are generated by using the frequency of fold change 
#values per gene within each set. Helpful to interpret up/down-regulated pathways."
ridgeplot(gse_fly) + labs(x = "Enrichment Distribution")
fly_dotplot <-dotplot(gse_fly, showCategory = 20, title = "Enriched MF Pathways - D. MELANOGASTER WHOLE BRAIN" , 
                      split=".sign") + facet_grid(.~.sign)


################################################################UP
fly_up = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/fly_up.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list_fly_up <- fly_up$log2FoldChange

# name the vector
names(original_gene_list_fly_up) <- fly_up$X

# omit any NA values 
gene_list_fly_up<-na.omit(original_gene_list_fly_up)

# sort the list in decreasing order (required for clusterProfiler)
gene_list_fly_up = sort(gene_list_fly_up, decreasing = TRUE)

keytypes(org.Dm.eg.db)#what kind of gene identifers can I use?

gse_fly_up <- gseGO(geneList=gene_list_fly_up, 
                 ont ="MF", 
                 keyType = "FLYBASE", 
                 nPerm = 10000, 
                 minGSSize = 3, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.05, 
                 verbose = TRUE, 
                 OrgDb = organism_f, 
                 pAdjustMethod = "none")



#"Grouped by gene set, density plots are generated by using the frequency of fold change 
#values per gene within each set. Helpful to interpret up/down-regulated pathways."
fly_up_ridgeplot <-ridgeplot(gse_fly_up, showCategory = 20) + labs(x = "Enrichment Distribution", title = "Enriched UPREGULATED MF Pathways - D. MELANOGASTER WHOLE BRAIN")

################################################################DOWN
fly_down = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/fly_down.csv", header=TRUE)

# we want the log2 fold change 
original_gene_list_fly_down <- fly_down$log2FoldChange

# name the vector
names(original_gene_list_fly_down) <- fly_down$X

# omit any NA values 
gene_list_fly_down<-na.omit(original_gene_list_fly_down)

# sort the list in decreasing order (required for clusterProfiler)
gene_list_fly_down = sort(gene_list_fly_down, decreasing = TRUE)

keytypes(org.Dm.eg.db)#what kind of gene identifers can I use?

gse_fly_down <- gseGO(geneList=gene_list_fly_down, 
                    ont ="MF", 
                    keyType = "FLYBASE", 
                    nPerm = 10000, 
                    minGSSize = 3, 
                    maxGSSize = 500, 
                    pvalueCutoff = 0.05, 
                    verbose = TRUE, 
                    OrgDb = organism_f, 
                    pAdjustMethod = "none")



#"Grouped by gene set, density plots are generated by using the frequency of fold change 
#values per gene within each set. Helpful to interpret up/down-regulated pathways."
fly_down_ridgeplot <-ridgeplot(gse_fly_down, showCategory = 20) + labs(x = "Enrichment Distribution", title = "Enriched DOWNREGULATED MF Pathways - D. MELANOGASTER WHOLE BRAIN")

grid.arrange(fly_up_ridgeplot, fly_down_ridgeplot, ncol=2)

#[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
#Bombus ontology

organism_f = "org.Dm.eg.db" #setting desired organism
BiocManager::install(organism_f, character.only = TRUE)
library(organism_f, character.only = TRUE)#bioconductor organism annotation library

fly = read.csv("C:/Users/trott/OneDrive/Desktop/Pena Lab/Senior_Thesis/res_f.csv", header=TRUE)
